spring.application.name=shop
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Development
spring.thymeleaf.cache=false

# Session Configuration
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=30d
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.domain=theartsarcade.shop
server.servlet.session.cookie.name=CLOTH_SHOP_SESSION
server.forward-headers-strategy=native

# Multipart File Uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-part-count=50

# Admin Configuration
app.admin.username=${ADMIN_USER}
app.admin.password=${ADMIN_PASS}

